//-----------------main-class-name----------------------//
export const grid_item_resize_text = '⊿'
export const grid_container_class_name = 'grid-container'
export const grid_item_class_name = 'grid-item'
//-------------------class-name----------------------//
export const grid_dragging_source_el = 'grid-dragging-source-el'
export const grid_dragging_clone_el = 'grid-dragging-clone-el'
export const grid_resizing_source_el = 'grid-resizing-source-el'
export const grid_resizing_clone_el = 'grid-resizing-clone-el'
export const grid_item_resizable_handle = 'grid-item-resizable-handle'
export const grid_item_content = 'grid-item-content'
export const grid_clone_el = 'grid-clone-el'
export const grid_item_mask = 'grid-item-mask'
//--------------------cursor-type-------------------------//
export const cursor_type_default = 'default'
export const cursor_type_mousedown = 'mousedown'
export const cursor_type_in_container = 'in-container'
export const cursor_type_item_resize = 'item-resize'
export const cursor_type_no_drop = 'no-drop'
export const cursor_type_static_no_drop = 'static-no-drop'
export const cursor_type_drag_to_item_no_drop = 'drag-to-item-no-drop'
export const cursor_type_not_found = 'notFound'
//--------------------grid_cursor-class-name-------------------------//
export const grid_cursor_PREFIX_HEADER = 'grid-cursor'
export const grid_cursor_default = 'grid-cursor-default'
export const grid_cursor_in_container = 'grid-cursor-in-container'
export const grid_cursor_mousedown = 'grid-cursor-mousedown'
export const grid_cursor_no_drop = 'grid-cursor-no-drop'
export const grid_cursor_static_item = 'grid-cursor-static-item'
export const grid_cursor_drag_to_item = 'grid-cursor-drag-to-item'
export const grid_cursor_item_resize = 'grid-cursor-item-resize'

