export const layoutData11 = [
    // {pos: {w: 1, h: 1, x: 5, y: 1}, static: true, close: false},
    // {pos: {w: 1, h: 2, x: 2, y: 1}, static: true, draggable: false},
    // {pos: {w: 1, h: 2, x: 1, y: 2}, static: true, resize: false},
    {pos: {w: 2, h: 2, x: 4, y: 2}, static: true},
    // {pos: {w: 1, h: 2, x: 3, y: 4}, static: true},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
]

export const layoutData22 = [
    // {pos: {w: 1, h: 1, x: 5, y: 1}, static: true, close: false},
    // {pos: {w: 1, h: 2, x: 2, y: 1}, static: true, draggable: false},
    // {pos: {w: 1, h: 2, x: 1, y: 2}, static: true, resize: false},
    // {pos: {w: 2, h: 2, x: 4, y: 2}, static: true},
    // {pos: {w: 1, h: 2, x: 3, y: 4}, static: true},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 4, h: 3}, nested: true},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
]

export const layoutData = [
    // {pos: {w: 4, h: 4, x: 1, y: 2, maxW: 5, minW: 3}, static: true },
    // {pos: {w: 1, h: 2, x: 5, y: 3}, static: true },
    // {pos: {w: 1, h: 2, x: 8, y: 2}, static: true},
    // {pos: {w: 2, h: 2, x: 8, y: 12}, static: true},
    // {pos: {w: 1, h: 2, x: 7, y: 10}, static: true},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 4, h: 3}},

    {pos: {w: 1, h: 1}},
    // {pos: {w: 2, h: 1}},
    // {pos: {w: 1, h: 2}},
    // {pos: {w: 1, h: 1}},
    // {pos: {w: 1, h: 2}},
    // {pos: {w: 1, h: 1}},
    // {pos: {w: 2, h: 2}},
    // {pos: {w: 2, h: 1}},
    // {pos: {w: 1, h: 1}},
    // {pos: {w: 1, h: 2}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 2, h: 2}},
    {pos: {w: 2, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 2, h: 2}},
    {pos: {w: 2, h: 1}},
    {pos: {w: 2, h: 4}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 2}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 2, h: 2}},
    {pos: {w: 2, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 2, h: 2}},
    {pos: {w: 2, h: 1}},
    {pos: {w: 2, h: 4}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 2}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 2, h: 2}},
    {pos: {w: 2, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 2, h: 2}},
    {pos: {w: 2, h: 1}},
    {pos: {w: 2, h: 4}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 2}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 2, h: 2}},
    {pos: {w: 2, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 2, h: 2}},
    {pos: {w: 2, h: 1}},
    {pos: {w: 2, h: 4}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 2}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 2, h: 2}},
    {pos: {w: 2, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 2, h: 2}},
    {pos: {w: 2, h: 1}},
    {pos: {w: 2, h: 4}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 2}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 2, h: 2}},
    {pos: {w: 2, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 2, h: 2}},
    {pos: {w: 2, h: 1}},
    {pos: {w: 2, h: 4}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 2}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 2, h: 2}},
    {pos: {w: 2, h: 1}},
    {pos: {w: 1, h: 1}},
    {pos: {w: 2, h: 2}},
    {pos: {w: 2, h: 1}},
    {pos: {w: 2, h: 4}},

]
